# These are supported funding model platforms

github: [trapexit]
patreon: trapexit
open_collective: trapexit
ko_fi: trapexit
custom: ['https://paypal.me/trapexit','https://www.subscribestar.com/trapexit']
